Danny palma
faztcommunity/community-match-backend pull request #8
Opened 2020-11-03 20:50 UTC by hola-sebas

refactor: refactorized the code in the class app

2020-11-03 21:21 UTC, DanoRysJan commented
async listen() ya es una promesa, no es necesario retornar Server para este proyecto.

2020-11-03 22:10 UTC, hola-sebas commented
ya no retorna server

2020-11-04 12:37 UTC, Blopaa reviewed
no hay necesidad de implementar server de http y cambiar la funcion de listen.
SI lo ves necesario, detalla por que, tambien hay que arreglar conflictos

2020-11-04 13:02 UTC, hola-sebas commented
# La necesidad
### Funcion listen
la necesidad de cambiar la funcion listen es porque no hay nada asincrono ahí y se algo de codigo que es un poco basura ya que se creaba una funcion asincrona para ejecutar el listening que luego era totalmente sincrono, y ps el parametro que recibe listen una funcion que se puede cambiar si es necesario con el simple echo de que le pases la funcion que quiera que ejecute luego de la creacion del server, si no se pasa ninguna hace `console.log`
### que retorne server
el que retorne el servidor creado era por si se necesitaba pero al parecer ya no
### Cambiar la exportacion a default de app
se exporta por default la clase app ya que no se exporta alguna otra cosa
### Pasar a publica la propiedad app
el que este la propiedad app publica es por temas de que si se quiere cambiar luego la propiedad no se tenga que cambiar la clase si no que se pueda cambiar por otro lado.
todo esto es de mi vista un poco noob? si crees que no es necesario me explicas el porque porfa

2020-11-04 19:41 UTC, Blopaa requested changes
![image](https://user-images.githubusercontent.com/63864637/98159539-0f67d200-1edd-11eb-9819-d06759543c32.png)
![image](https://user-images.githubusercontent.com/63864637/98159580-20b0de80-1edd-11eb-8c9b-910d1f966215.png)
app debe privado, no se debe modificar en ninguna otra parte.
la funcion de main esta bien no hace falta cambiarla, es demostrativa de que se ejecuta

2020-11-04 20:06 UTC, hola-sebas commented
en fin ya veo que no hay necesidad de cambiar el app asi que lo voy a cerrar u.u

2020-11-04 20:06 UTC, closed without merging